// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.1
// source: proto/keywords.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatGPTKeywordsClient is the client API for ChatGPTKeywords service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatGPTKeywordsClient interface {
	FindAll(ctx context.Context, in *FindAllReq, opts ...grpc.CallOption) (*FindAllRes, error)
}

type chatGPTKeywordsClient struct {
	cc grpc.ClientConnInterface
}

func NewChatGPTKeywordsClient(cc grpc.ClientConnInterface) ChatGPTKeywordsClient {
	return &chatGPTKeywordsClient{cc}
}

func (c *chatGPTKeywordsClient) FindAll(ctx context.Context, in *FindAllReq, opts ...grpc.CallOption) (*FindAllRes, error) {
	out := new(FindAllRes)
	err := c.cc.Invoke(ctx, "/chatgpt_keywords.ChatGPTKeywords/FindAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatGPTKeywordsServer is the server API for ChatGPTKeywords service.
// All implementations must embed UnimplementedChatGPTKeywordsServer
// for forward compatibility
type ChatGPTKeywordsServer interface {
	FindAll(context.Context, *FindAllReq) (*FindAllRes, error)
	mustEmbedUnimplementedChatGPTKeywordsServer()
}

// UnimplementedChatGPTKeywordsServer must be embedded to have forward compatible implementations.
type UnimplementedChatGPTKeywordsServer struct {
}

func (UnimplementedChatGPTKeywordsServer) FindAll(context.Context, *FindAllReq) (*FindAllRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedChatGPTKeywordsServer) mustEmbedUnimplementedChatGPTKeywordsServer() {}

// UnsafeChatGPTKeywordsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatGPTKeywordsServer will
// result in compilation errors.
type UnsafeChatGPTKeywordsServer interface {
	mustEmbedUnimplementedChatGPTKeywordsServer()
}

func RegisterChatGPTKeywordsServer(s grpc.ServiceRegistrar, srv ChatGPTKeywordsServer) {
	s.RegisterService(&ChatGPTKeywords_ServiceDesc, srv)
}

func _ChatGPTKeywords_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatGPTKeywordsServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatgpt_keywords.ChatGPTKeywords/FindAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatGPTKeywordsServer).FindAll(ctx, req.(*FindAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatGPTKeywords_ServiceDesc is the grpc.ServiceDesc for ChatGPTKeywords service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatGPTKeywords_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatgpt_keywords.ChatGPTKeywords",
	HandlerType: (*ChatGPTKeywordsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAll",
			Handler:    _ChatGPTKeywords_FindAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/keywords.proto",
}
