// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.1
// source: proto/sensitive.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatGPTSensitiveClient is the client API for ChatGPTSensitive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatGPTSensitiveClient interface {
	Validate(ctx context.Context, in *ValidateReq, opts ...grpc.CallOption) (*ValidateRes, error)
}

type chatGPTSensitiveClient struct {
	cc grpc.ClientConnInterface
}

func NewChatGPTSensitiveClient(cc grpc.ClientConnInterface) ChatGPTSensitiveClient {
	return &chatGPTSensitiveClient{cc}
}

func (c *chatGPTSensitiveClient) Validate(ctx context.Context, in *ValidateReq, opts ...grpc.CallOption) (*ValidateRes, error) {
	out := new(ValidateRes)
	err := c.cc.Invoke(ctx, "/chatgpt_sensitive.ChatGPTSensitive/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatGPTSensitiveServer is the server API for ChatGPTSensitive service.
// All implementations must embed UnimplementedChatGPTSensitiveServer
// for forward compatibility
type ChatGPTSensitiveServer interface {
	Validate(context.Context, *ValidateReq) (*ValidateRes, error)
	mustEmbedUnimplementedChatGPTSensitiveServer()
}

// UnimplementedChatGPTSensitiveServer must be embedded to have forward compatible implementations.
type UnimplementedChatGPTSensitiveServer struct {
}

func (UnimplementedChatGPTSensitiveServer) Validate(context.Context, *ValidateReq) (*ValidateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedChatGPTSensitiveServer) mustEmbedUnimplementedChatGPTSensitiveServer() {}

// UnsafeChatGPTSensitiveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatGPTSensitiveServer will
// result in compilation errors.
type UnsafeChatGPTSensitiveServer interface {
	mustEmbedUnimplementedChatGPTSensitiveServer()
}

func RegisterChatGPTSensitiveServer(s grpc.ServiceRegistrar, srv ChatGPTSensitiveServer) {
	s.RegisterService(&ChatGPTSensitive_ServiceDesc, srv)
}

func _ChatGPTSensitive_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatGPTSensitiveServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatgpt_sensitive.ChatGPTSensitive/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatGPTSensitiveServer).Validate(ctx, req.(*ValidateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatGPTSensitive_ServiceDesc is the grpc.ServiceDesc for ChatGPTSensitive service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatGPTSensitive_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatgpt_sensitive.ChatGPTSensitive",
	HandlerType: (*ChatGPTSensitiveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _ChatGPTSensitive_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sensitive.proto",
}
